// User types
export const SET_USER = 'SET_USER';

// Search filters
export const SET_PRICE_FILTER = 'SET_PRICE_FILTER';
export const SET_MATERIAL_FILTER = 'SET_MATERIAL_FILTER';
export const SET_SIZE_FILTER = 'SET_SIZE_FILTER';
export const SET_ART_TYPE_FILTER = 'SET_ART_TYPE_FILTER';

// Admin
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const UPDATE_MODAL_INFORMATION = 'UPDATE_MODAL_INFORMATION';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_AND_REDIRECT_USER = 'AUTHENTICATE_AND_REDIRECT_USER';
